
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOCNO_CONTENT DOCNO_END DOCNO_START DOC_END DOC_START TEXTdocument : DOC_START DOCNO_START DOCNO_CONTENT DOCNO_END TEXT DOC_END'
    
_lr_action_items = {'DOC_START':([0,],[2,]),'$end':([1,7,],[0,-1,]),'DOCNO_START':([2,],[3,]),'DOCNO_CONTENT':([3,],[4,]),'DOCNO_END':([4,],[5,]),'TEXT':([5,],[6,]),'DOC_END':([6,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'document':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> document","S'",1,None,None,None),
  ('document -> DOC_START DOCNO_START DOCNO_CONTENT DOCNO_END TEXT DOC_END','document',6,'p_document','lex_yacc_parser.py',37),
]
